services:
  - type: web
    name: task-management-api
    runtime: node
    rootDir: api
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: MONGODB_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
